M48
; DRILL file {KiCad 8.0.2} date 2024-06-25T21:59:00+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-25T21:59:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X147.0Y-36.0
X147.0Y-81.5
X237.0Y-36.0
X237.0Y-81.0
M30
